[package]

name = "pcp"
version = "0.1.3"
authors = [ "Pierre Talbot <ptalbot@hyc.io>" ]

[lib]

name = "pcp"
path = "src/libpcp/lib.rs"
crate_type = ["rlib", "dylib"]

[dependencies]

intervallum = "^0.5.5"
gcollections = "^0.2.2"
num = "^0.1.29"

[dependencies.vec_map]
version = "0.6.0"
