[package]

name = "pcp"
version = "0.1.0"
authors = [ "Pierre Talbot <ptalbot@hyc.io>" ]

[lib]

name = "pcp"
path = "src/libpcp/lib.rs"
crate_type = ["dylib"]

[dependencies]

intervallum = "^0.3.0"
num = "^0.1.22"
