[package]

name = "pcp"
version = "0.1.0"
authors = [ "Pierre Talbot <ptalbot@hyc.io>" ]

[lib]

name = "pcp"
path = "src/libpcp/lib.rs"
crate_type = ["rlib", "dylib"]

[dependencies]

intervallum = "0.4.9"
num = "0.1.27"

[dependencies.vec_map]
git="https://github.com/ptal/vec-map"
version = "0.3.0"
features = ["nightly"]
