[package]

name = "pcp"
version = "0.1.1"
authors = [ "Pierre Talbot <ptalbot@hyc.io>" ]

[lib]

name = "pcp"
path = "src/libpcp/lib.rs"
crate_type = ["rlib", "dylib"]

[dependencies]

intervallum = "0.4.11"
num = "0.1.29"

[dependencies.vec_map]
version = "0.4.0"
features = ["nightly"]
