[package]

name = "pcp"
version = "0.2.1"
authors = [ "Pierre Talbot <ptalbot@hyc.io>" ]

[lib]

name = "pcp"
path = "src/libpcp/lib.rs"
crate_type = ["rlib", "dylib"]

[dependencies]

intervallum = "^0.6.4"
gcollections = "^0.3.3"
num = "^0.1.29"
bit-set = "^0.4.0"

[dependencies.vec_map]
version = "0.6.0"
